title: "Indicateurs ODD — Sénégal"
description: "Plateforme nationale de suivi des ODD au Sénégal. ANSD / DMCI."
baseurl: "/odd-senegal-site"
url: "https://ndaosaer.github.io"

remote_theme: open-sdg/open-sdg@2.3.0

remote_data_prefix: "https://ndaosaer.github.io/odd-senegal-data"

languages:
  - fr

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

collections:
  indicators:
    output: true
  goals:
    output: true
  posts:
    output: true

create_indicators:
  layout: indicator

create_goals:
  layout: goal

create_pages:
  pages:
    - folder: /
      layout: frontpage
    - folder: /goals
      layout: goals
    - folder: /reporting-status
      layout: reportingstatus
    - folder: /search
      layout: search
    - folder: /about
      layout: page
    - folder: /faq
      layout: faq

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - scripts
  - Makefile
