title: "Indicateurs ODD — Sénégal"
description: "Plateforme nationale de suivi des ODD au Sénégal. ANSD / DMCI — Agenda 2030."
baseurl: "/odd-senegal-site"
url: "https://ndaosaer.github.io"

remote_theme: open-sdg/open-sdg@2.3.0

remote_data_prefix: "https://ndaosaer.github.io/odd-senegal-data"

languages:
  - fr

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
