- name: reporting_status
  field: reporting_status
  label: Reporting Status
  widget: select
  options:
    - label: Complete
      value: complete
    - label: In Progress
      value: inprogress
    - label: Not Started
      value: notstarted
    - label: Not Applicable
      value: notapplicable

- name: indicator_name
  field: indicator_name
  label: Indicator Name
  widget: text

- name: indicator_number
  field: indicator_number
  label: Indicator Number
  widget: text

- name: target_id
  field: target_id
  label: Target ID
  widget: text

- name: goal_meta_link
  field: goal_meta_link
  label: Goal Metadata Link
  widget: text

- name: national_geographical_coverage
  field: national_geographical_coverage
  label: Geographic Coverage
  widget: text

- name: computation_units
  field: computation_units
  label: Unit of Measurement
  widget: text

- name: source_active_1
  field: source_active_1
  label: Source Active
  widget: boolean

- name: source_organisation_1
  field: source_organisation_1
  label: Source Organisation
  widget: text

- name: source_periodicity_1
  field: source_periodicity_1
  label: Source Periodicity
  widget: text
