analytics:
  ua: ''
  gtag: ''

country:
  name: Senegal
  adjective: Senegalese

remote_data_prefix: "https://ndaosaer.github.io/odd-senegal-data"

repository_url_data: https://github.com/ndaosaer/odd-senegal-data
repository_url_site: https://github.com/ndaosaer/odd-senegal-site

email_contacts:
  questions: contact@ansd.sn
  suggestions: contact@ansd.sn
  functional: contact@ansd.sn

hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true

graph_color_set: accessible
graph_color_headline: '#004466'

environment: staging

cookie_consent_form:
  enabled: false

indicator_config_form:
  enabled: false

indicator_data_form:
  enabled: false

site_config_form:
  enabled: false

automated_translation: false
